# -*- coding: utf-8 -*-
"""cars24ML_Model_Training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JWv4KS-imvzQjK0ue1POL6p-0i5GcvzP
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/car_price.csv')
df.head()

df1 = df.copy()

#make column is not numerical , then what to do ?? how to convert this string as numerical value ......
# level encoding is one of the option ??
# for my algorithm bmw>maruti>kia this should be visible in our value , that's why level encoding is not good
# we need importance value weighatage
# we can replace these string with average of selling price ---->

df1.loc[:,"make"]=df1.groupby(["make"])["selling_price"].transform("mean")

df1

from sklearn.model_selection import train_test_split
y=df1["selling_price"]
df1.drop(columns=["selling_price"],inplace=True)

X_train,X_test,y_train,y_test= train_test_split(df1,y,test_size=0.2,random_state=10)

X_train

X_test

y_train

y_test

from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train, y_train)

lr.coef_

lr.intercept_

y_pred = lr.predict(X_test)

from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

X_train.columns

lr.predict([[60000, 15, 1197, 80,  5, 20.902500, 1, 1, 1,0,0,0,1,0,1]])

import pickle
pickle_out = open("lr.pkl","wb")
pickle.dump(lr, pickle_out)
pickle_out.close()

# ! pip install streamlit -q
# !wget -q -O - ipv4.icanhazip.com
# ! streamlit run /content/app.py & npx localtunnel --port 8501

# !npx localtunnel --port 8501

# !pip install streamlit -q
# !wget -q -O - ipv4.icanhazip.com
# import time
# !streamlit run /content/app.py &
# time.sleep(5)
# !npx localtunnel --port 8501

# !streamlit run /content/app.py

